Feat/header
janle/nivu-restaurant pull request #2
Opened 2020-09-21 19:37 UTC by eliohk

Edited header according to the sketches that were produced, also made some _suggestions_ regarding other components within the header.

2020-09-21 19:42 UTC, eliohk commented
Screenshot of the header after changes.

![Skjermbilde 2020-09-21 kl  21 41 43](https://user-images.githubusercontent.com/60292243/93813344-464a9700-fc53-11ea-9c6b-1aca6809f45e.png)

2020-09-21 21:43 UTC, eliohk commented
Screenshot of header after changes

![Skjermbilde 2020-09-21 kl  23 41 41](https://user-images.githubusercontent.com/60292243/93824664-1a83dd00-fc64-11ea-96d9-918047e9ac39.png)

2020-09-22 15:07 UTC, janle requested changes

2020-09-23 17:19 UTC, janle requested changes

2020-09-23 17:19 UTC, janle commented on src/components/Header/header.less
> +    display: flex-row;
Litt usikker på om denne linjen støttes av alle browsere.
Kan heller skrives slik:
`display: flex;`
`flex-direction: row;`

2020-09-23 17:19 UTC, janle commented on src/components/Header/header.less
> +        color: #e8ae31;
Hvorfor denne fargen?

2020-09-23 17:19 UTC, janle commented on src/components/Header/header.tsx
> +                <Link to = "" className={styles.logo}>NiVu</Link>
`<Link to = "/" className={styles.logo}>NiVu</Link>`

2020-09-23 17:19 UTC, janle commented on src/components/Header/header.tsx
> +                <Link to = "\meny" className={styles.link}>Meny</Link>
`<Link to = "/meny" className={styles.link}>Meny</Link>`

2020-09-23 17:19 UTC, janle commented on src/components/Header/header.tsx
> +                <Link to = "\kontakt-oss" className={styles.link}>Kontakt oss</Link>
`<Link to = "/kontakt-oss" className={styles.link}>Kontakt oss</Link>`

2020-09-23 18:43 UTC, eliohk commented on src/components/Header/header.less
> +        color: #e8ae31;
Tok en tilfeldig farge som så grei ut, skal den bare defaultes til hvit?

2020-09-23 18:59 UTC, janle approved these changes

2020-09-23 18:59 UTC, merged